# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45ceec334b8871bba784156ecd1b436442098abd3e5f3f94c0c483ce528e9792449011889d87b0f5069362366160719a49af334863e81aba34f32dc15edffb21

test:
  secret_key_base: dcb50686d568e0f2655c39c3b0cd560d366abd368bb5db2d1cf66eb214021473e1f8f333495315fb89b503ca1e374841261dce5c13240656880bf5dbdcce1cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
